name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # Chạy mỗi 30 phút
  workflow_dispatch: # Cho phép chạy thủ công

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [frontend, master]      # Định nghĩa danh sách các nhánh cần sync
      fail-fast: false                  # Nếu một nhánh lỗi, nhánh kia vẫn chạy tiếp
    steps:
      - name: Checkout Target Branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ matrix.branch }}     # Checkout Code của nhánh trong matrix (frontend hoặc master)
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Sync with Upstream
        run: |
          git remote add upstream https://github.com/simonnguyen175/volunteer-hub.git
          git fetch upstream

          # Đảm bảo đang ở đúng nhánh cần sync
          git checkout ${{ matrix.branch }}

          # Merge code từ nhánh tương ứng của upstream
          git merge upstream/${{ matrix.branch }} --allow-unrelated-histories -m "Auto-sync from upstream"

          # Đẩy code lên Fork
          git push origin ${{ matrix.branch }}
